// Generated by CoffeeScript 1.8.0
(function() {
  var app, io;

  app = require('express').createServer();

  io = require('socket.io')(app);

  app.listen(80);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  });

  io.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'hi'
    });
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
