// Generated by CoffeeScript 1.8.0
(function() {
  console.log(Math.round(3.1, Math.round(5.2)));

  console.log(Math.round(3.1, Math.round(5.2)));

}).call(this);

//# sourceMappingURL=console.log().js.map
