// Generated by CoffeeScript 1.8.0
(function() {
  var greeting;

  greeting = function(subject) {
    return "hello a" + subject;
  };

  console.log(greeting('test'));

}).call(this);

//# sourceMappingURL=arg-fun.js.map
