// Generated by CoffeeScript 1.8.0
(function() {
  var greeting;

  greeting = function() {
    return "hello, " + arguments[0];
  };

  console.log(greeting("hello", "hello2"));

}).call(this);

//# sourceMappingURL=arg-fun2.js.map
