// Generated by CoffeeScript 1.8.0
(function() {
  (function() {
    return 'Hello, functions!';
  });

  console.log((function() {
    return 'Hello, functions!';
  })());

}).call(this);

//# sourceMappingURL=hello-fun.js.map
