// Generated by CoffeeScript 1.8.0

/*冒泡排序，从小到大 */

(function() {
  var arr, bubbleSort;

  bubbleSort = function(arr) {
    var inner, numElements, outer, tmp, _results;
    numElements = arr.length;
    outer = numElements;
    _results = [];
    while (outer >= 2) {
      inner = 0;
      while (inner <= outer - 2) {
        console.log("outer - 2 ==>", outer - 2);
        if (arr[inner] > arr[inner + 1]) {
          tmp = arr[inner];
          arr[inner] = arr[inner + 1];
          arr[inner + 1] = tmp;
        }
        console.log(arr);
        inner++;
      }
      _results.push(outer--);
    }
    return _results;
  };

  arr = [4, 3, 2, 1, 31, 314, 134, 123, 3, 21, 3, 21, 3, 21, 3, 21, 3];

  console.log(arr);

  bubbleSort(arr);

  console.log(arr);

}).call(this);

//# sourceMappingURL=bubble_sort.js.map
