// Generated by CoffeeScript 1.8.0
(function() {
  var async, fn, log, t;

  async = require('async');

  t = require('./t.js');

  log = t.log;

  fn = async.applyEach([
    function(name, cb) {
      return setTimeout(function() {
        log('1.2 handle: ' + name + ' A');
        return cb(null, '123');
      }, 500);
    }, function(name, cb) {
      return setTimeout(function() {
        log('1.2 handle ' + name + ' B');
        return cb('B');
      }, 300);
    }
  ]);

  fn('simple', function(err, res) {
    log('err: ', err);
    return log('res: ', res);
  });

}).call(this);

//# sourceMappingURL=applyEach_ex_1.2.js.map
