// Generated by CoffeeScript 1.8.0
(function() {
  var async, fn, inc, log, t;

  async = require('async');

  t = require('./t.js');

  log = t.log;

  inc = function(a, b, callback, timeout) {
    if (timeout == null) {
      timeout = 200;
    }
    t.wait(200);
    return setTimeout(function() {
      return callback(null, a + b);
    }, timeout);
  };

  fn = async.apply(inc, 1, 2);

  fn(function(err, n) {
    return log('inc:' + n);
  });

}).call(this);

//# sourceMappingURL=apply_ex2.js.map
