// Generated by CoffeeScript 1.8.0
(function() {
  var async;

  async = require('async');

  async.auto({
    oneFun: function(cb) {
      var a, b;
      a = 123;
      b = 456;
      console.log("hello");
      return cb(null, a, b, "123");
    },
    towFun: [
      "oneFun", function(cb, result) {
        console.log("123");
        return console.log(result);
      }
    ]
  });

}).call(this);

//# sourceMappingURL=test_auto.js.map
