// Generated by CoffeeScript 1.8.0
(function() {
  var age, ageFun;

  age = 99;

  ageFun = function() {
    return age = 0;
  };

  ageFun();

  console.log("my age is " + age);

}).call(this);

//# sourceMappingURL=var.js.map
