// Generated by CoffeeScript 1.8.0
(function() {
  var age, ageFun;

  ageFun = function() {
    var age;
    return age = 0;
  };

  age = 99;

  ageFun();

  console.log("my age is " + age);

}).call(this);

//# sourceMappingURL=var2.js.map
