// Generated by CoffeeScript 1.8.0
(function() {
  var ageFun;

  ageFun = function() {
    var age;
    return age = 0;
  };

  ageFun();

  console.log("i'm age " + age);

}).call(this);

//# sourceMappingURL=var3.js.map
