// Generated by CoffeeScript 1.8.0
(function() {
  var fun1, x;

  x = 5;

  fun1 = function(x) {
    return x * 5;
  };

  console.log(fun1(2));

  console.log(x);

}).call(this);

//# sourceMappingURL=var4.js.map
