// Generated by CoffeeScript 1.8.0
(function() {
  var a, clearArray;

  clearArray = function(arr) {
    arr.splice(0, arr.length);
  };

  a = [1, 2, 3, 4, 5, 6];

  console.log(clearArray(a));

}).call(this);

//# sourceMappingURL=clearArray.js.map
