// Generated by CoffeeScript 1.8.0
(function() {
  var fun, run,
    __slice = [].slice;

  run = function() {
    var arg, fun;
    fun = arguments[0], arg = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return fun.apply(fun, arg);
  };

  fun = function(a, b) {
    return console.log(a, b);
  };

  run(fun, '1', '2');

}).call(this);

//# sourceMappingURL=run.js.map
