// Generated by CoffeeScript 1.8.0
(function() {
  var odd;

  odd = function(num) {
    if (typeof num === 'number') {
      if (num === Math.round(num)) {
        if (num > 0) {
          return num % 2 === 1;
        } else {
          return console.log("" + num + " is not positive");
        }
      } else {
        return console.log("" + num + " is not integer");
      }
    } else {
      return console.log("" + num + " is not a number");
    }
  };

  console.log(odd(120));

}).call(this);

//# sourceMappingURL=is.js.map
