// Generated by CoffeeScript 1.8.0
(function() {
  var WebSocketServer, stock_request, stocks, wss;

  WebSocketServer = require("ws").Server;

  wss = new WebSocketServer({
    port: 8181
  });

  stock_request = {
    "stocks": ["AAPL", "MSFT", "AMZN", "GOOG", "YHOO"]
  };

  stocks = {
    "AAPL": 0,
    "MSFT": 0,
    "AMZN": 0,
    "GOOG": 0,
    "YHOO": 0
  };

  ws.open = function(e) {
    console.log("Connection established");
    return ws.send(JSON.stringify(stock_request));
  };

  ws.onerror = function(e) {
    console.log("WebSocket failure, error", e);
    return handleErrors(e);
  };

  ws.onclose = function(e) {
    var symbol, _results;
    console.log("WebSocket connection closed", e);
    _results = [];
    for (symbol in stocks) {
      if (stocks.hasOwnProperty(symbol)) {
        _results.push(stocks[symbol] = 0);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

}).call(this);

//# sourceMappingURL=server.js.map
