// Generated by CoffeeScript 1.8.0
(function() {
  exports.testPony = function(test) {
    var isPony;
    isPony = true;
    test.ok(isPony, 'This is not a pony.');
    return test.done();
  };

}).call(this);

//# sourceMappingURL=nodeunit.js.map
