// Generated by CoffeeScript 1.8.0
(function() {
  var root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  root.emergencyNumber = 911;

}).call(this);

//# sourceMappingURL=file1.js.map
