// Generated by CoffeeScript 1.8.0
(function() {
  var a, i, _i, _len;

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  for (_i = 0, _len = a.length; _i < _len; _i++) {
    i = a[_i];
    if (i === 2) {
      return console.log("hello");
    }
    console.log(i);
  }

}).call(this);

//# sourceMappingURL=for.js.map
