// Generated by CoffeeScript 1.8.0
(function() {
  var callback;

  callback = (function(_this) {
    return function(message) {
      return _this.email = email;
    };
  })(this);

}).call(this);

//# sourceMappingURL=this4.js.map
