// Generated by CoffeeScript 1.8.0
(function() {
  var pig, setName;

  setName = function(name) {
    return this.name = name;
  };

  pig = {};

  setName.apply(pig, ["hello"]);

  console.log(pig);

}).call(this);

//# sourceMappingURL=this3.js.map
