// Generated by CoffeeScript 1.8.0
(function() {
  var a, setName;

  setName = function(name) {
    this.name = name;
    return this.name2 = "hello";
  };

  a = new setName("youqing");

  console.log(a);

}).call(this);

//# sourceMappingURL=this.js.map
