// Generated by CoffeeScript 1.8.0
(function() {
  var cat, setName;

  setName = function(name) {
    return this.name = name;
  };

  cat = {};

  cat.setName = setName;

  cat.setName("youqing");

  console.log(cat);

}).call(this);

//# sourceMappingURL=this2.js.map
