// Generated by CoffeeScript 1.8.0
(function() {
  var i, later, occurrences, sched, _i, _len, _ref;

  later = require('later');

  sched = later.parse.text('every 5 mins');

  occurrences = later.schedule(sched).next(10);

  _ref = 10;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    console.log(occurrences[i]);
  }

}).call(this);

//# sourceMappingURL=ex1.js.map
