// Generated by CoffeeScript 1.8.0
(function() {
  var a, i, j, _i, _len;

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  for (j = _i = 0, _len = a.length; _i < _len; j = ++_i) {
    i = a[j];
    console.log(i);
    console.log(j);
  }

}).call(this);

//# sourceMappingURL=arr.js.map
