// Generated by CoffeeScript 1.8.0
(function() {
  var fs, owl2, word, wordList;

  fs = require('fs');

  owl2 = fs.readFileSync('OWL2.txt', 'utf8');

  wordList = owl2.match(/^(\w+)/mg);

  wordList = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = wordList.length; _i < _len; _i++) {
      word = wordList[_i];
      if (word.length <= GRID_SIZE) {
        _results.push(word);
      }
    }
    return _results;
  })();

}).call(this);

//# sourceMappingURL=game.js.map
