// Generated by CoffeeScript 1.8.0
(function() {
  var ddd;

  ddd = function($scope) {
    $scope.greeting = {
      text: 'hi12'
    };
  };

}).call(this);

//# sourceMappingURL=controllers.js.map
