// Generated by CoffeeScript 1.8.0
(function() {
  var refine,
    __slice = [].slice;

  refine = function() {
    var c, chaff, wheat, _i;
    wheat = arguments[0], chaff = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), c = arguments[_i++];
    console.log("The best: " + wheat);
    console.log("The rest: " + (chaff.join(', ')));
    return console.log("the rest: " + chaff);
  };

  refine("123", "hello");

}).call(this);

//# sourceMappingURL=arg....js.map
