// Generated by CoffeeScript 1.8.0
(function() {
  var a;

  a = function(b) {
    if (b == null) {
      b = 'hello';
    }
    return console.log(b);
  };

}).call(this);

//# sourceMappingURL=arg1.js.map
