// Generated by CoffeeScript 1.8.0
(function() {
  var chooseMeals, getRandomSubarray;

  chooseMeals = function(breakfast, lunch, dinner) {
    if (breakfast == null) {
      breakfast = 'waffles';
    }
    if (lunch == null) {
      lunch = 'gyros';
    }
    if (dinner == null) {
      dinner = 'pizza';
    }
    console.log("breakfast", breakfast);
    console.log("lunch", lunch);
    return console.log("dinner", dinner);
  };

  getRandomSubarray = function(arr, size) {
    var i, index, shuffled, temp;
    shuffled = arr.slice(0);
    i = arr.length;
    temp = "";
    index = "";
    while (i--) {
      index = Math.floor((i + 1) * Math.random());
      temp = shuffled[index];
      shuffled[index] = shuffled[i];
      shuffled[i] = temp;
    }
    return shuffled.slice(0, size);
  };

  console.log(getRandomSubarray("12345678", 5));

}).call(this);

//# sourceMappingURL=test.js.map
