// Generated by CoffeeScript 1.8.0
(function() {
  var WebSocketServer, wss;

  WebSocketServer = require("ws").Server;

  wss = new WebSocketServer({
    port: 8282
  });

  wss.on('connection', function(ws) {
    console.log('client connection');
    return ws.on('message', function(message) {
      return console.log(message);
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
