// Generated by CoffeeScript 1.8.0
(function() {
  var typeOfTires;

  typeOfTires = '';

  exports.init = function(type) {
    return typeOfTires = type;
  };

  exports.info = function() {
    return console.log("The car uses " + typeOfTires + " tires.");
  };

}).call(this);

//# sourceMappingURL=wheels.js.map
