// Generated by CoffeeScript 1.8.0
(function() {
  var baiduSwitch;

  baiduSwitch = function(x, y) {
    var url;
    url = "http://api.map.baidu.com/geoconv/v1/?form=3&to5&ak=5tlKe6382DLbgQmpoLoQc4ks&output=json&coords=" + x + "," + y;
    return request.get(url, function(err, res, body) {
      var data, msg;
      msg = {};
      if (err) {
        msg.code = "-1";
        msg.info = "request baidu error";
        return msg;
      }
      data = JSON.parse(body);
      if (data.status !== 0) {
        msg.code = "-1";
        msg.info = "json result error baidu";
        return msg;
      }
      msg.code = 1;
      msg.info = {
        x: data.result.x,
        y: data.result.y
      };
      return msg;
    });
  };

  console.log(baiduSwitch(113.3334256, 23.14737133));

}).call(this);

//# sourceMappingURL=baidu.js.map
