// Generated by CoffeeScript 1.8.0
(function() {
  var arr, x, _fn, _i, _len;

  arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  _fn = function(x) {
    return setTimeout((function() {
      return console.log(x);
    }), 0);
  };
  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    x = arr[_i];
    _fn(x);
  }

}).call(this);

//# sourceMappingURL=do.js.map
