// Generated by CoffeeScript 1.8.0
(function() {
  var Tribble, tribble1, tribble2;

  Tribble = (function() {
    function Tribble() {
      this.isAlive = true;
      this.count = 0;
      this.test();
    }

    Tribble.prototype.breed = function() {
      if (this.isAlive) {
        return new Tribble;
      }
    };

    Tribble.prototype.die = function() {
      if (this.isAlive) {
        this.count--;
      }
      return this.isAlive = false;
    };

    Tribble.prototype.test = function() {
      return console.log(this.count);
    };

    Tribble.count = 1;

    Tribble.makeTrouble = function() {
      var i;
      return console.log(((function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 1, _ref = this.count; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
          _results.push('Trouble!');
        }
        return _results;
      }).call(this)).join(' '));
    };

    return Tribble;

  })();

  tribble1 = new Tribble();

  tribble2 = new Tribble();

  Tribble.makeTrouble();

}).call(this);

//# sourceMappingURL=Tribble.js.map
