"""initial migration

Revision ID: 293624ea299f
Revises: None
Create Date: 2015-01-18 11:18:17.226770

"""

# revision identifiers, used by Alembic.
revision = '293624ea299f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
